Add prepare-commit-msg hook and guide
ydataai/playbook pull request #8
Opened 2020-09-23 21:26 UTC by rafaelcpalmeida

2020-09-24 07:49 UTC, portellaa requested changes

2020-09-24 07:49 UTC, portellaa commented on hooks/README.md
> +The following guid will show you how to add the task type to your commit messages, automatically, using git hooks.
guide

2020-09-24 07:49 UTC, portellaa commented on hooks/prepare-commit-msg
> +TRIMMED=$(echo $BRANCH_NAME | grep -Eo '^(\w+)' | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/')
just a suggestion easier to read and maintain: `$(echo $BRANCH_NAME | cut -d/ -f1)`

2020-09-24 07:49 UTC, portellaa commented on hooks/prepare-commit-msg
> +fi
missing new line

2020-09-24 07:49 UTC, portellaa commented on hooks/prepare-commit-msg
> +if [ -n "$BRANCH_NAME" ] && [[ $APPLY_TO_BRANCH -eq 1 ]]; then
to check if array contains something, you can just do `if [[ ${BRANCHES_TO_APPLY[*]} == *"$BRANCH"* ]]; then`, which replaces the `APPLY_TO_BRANCH` and the `if [ -n "$BRANCH_NAME" ] && [[ $APPLY_TO_BRANCH -eq 1 ]]; then`, but they are both ok

2020-09-24 07:50 UTC, portellaa commented
i think it misses the validation if the commit message already contains this and also you can't use contexts in the message

2020-09-24 09:04 UTC, portellaa commented on hooks/prepare-commit-msg
> +TRIMMED=$(echo $BRANCH_NAME | grep -Eo '^(\w+)' | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/')
you could use `tr`, `awk` or even `sed` with the `L` modifier to lowercase the values

2020-09-25 17:32 UTC, rafaelcpalmeida commented on hooks/prepare-commit-msg
> +TRIMMED=$(echo $BRANCH_NAME | grep -Eo '^(\w+)' | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/')
Thanks for those! 🔥

2020-09-25 18:22 UTC, rafaelcpalmeida commented
Managed to implement the validation whether the user's commit message already includes or not the prefix that the hook would append.

```bash
▶ git commit -m "teste"
[feat/teste b051396] feat: teste
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 h

▶ git commit -m "feat: teste"
[feat/teste 5512f68] feat: teste
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 i

▶ git commit -m "feat(teste): teste"
[feat/teste cf7516f] feat(teste): teste
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 j
```

2021-04-19 18:53 UTC, closed without merging